# Generated by Django 3.0.7 on 2020-06-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200612_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user',
        ),
    ]
